# This is a basic workflow to help you get started with Actions

name: Starter CI implementation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: NPM Install Dependencies 
        run: |
           echo Is npm installed?
           npm -v
           echo Is git installed?
           git --version
           echo Is Node installed?
           node -v
           echo Install Dependencies
           cd turboapp
           cd apps
           cd web
           npm i
           cd..
           cd backend
           npm i
           cd ..
           cd ..
           npm i

      - name: Build and Compile Backend
        run: |
           cd turboapp
           cd apps
           cd backend
           npm run build

      - name: Build and Compile Frontend
        run: |
           cd turboapp
           cd apps
           cd web
           npm run build
           

        
      
